enum ProvidersEnum {
  VIRTUAL_ASSISTANT_FUNCTIONS = 'VIRTUAL_ASSISTANT_FUNCTIONS_PROVIDER',
  VIRTUAL_ASSISTANT_SKILL = 'VIRTUAL_ASSISTANT_SKILL_PROVIDER',
  CHATBOT = 'CHATBOT_PROVIDER',
  STORAGE = 'STORAGE_PROVIDER',
}

export default ProvidersEnum;
